version: '3'
services:
  # basic-app:
  #   image: basic-app
  #   ports:
  #     - 3001:3001
  dbmongo:
    image: mongo
    restart: always
    ports:
      - 2701:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: dbmongo