version: '3'

services:
  db:
    container_name: docker-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    restart: always
    ports:
      - 7002:80